// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:1673

#include "managerI.h"

// Implementation skeleton constructor
Distrio_Manager_i::Distrio_Manager_i (void)
{
}

// Implementation skeleton destructor
Distrio_Manager_i::~Distrio_Manager_i (void)
{
}

::Distrio::Error * Distrio_Manager_i::digital (
  ::Distrio::Digital_list_out io_list)
{
  // Add your implementation here
}

::Distrio::Error * Distrio_Manager_i::analog (
  ::Distrio::Analog_list_out io_list)
{
  // Add your implementation here
}

::Distrio::Error * Distrio_Manager_i::device (
  ::Distrio::Device_list_out dev_list)
{
  // Add your implementation here
}

::Distrio::Error * Distrio_Manager_i::register_io_digital (
  ::Distrio::Analog_ptr io_ana)
{
  // Add your implementation here
}

::Distrio::Error * Distrio_Manager_i::register_io_analog (
  ::Distrio::Digital_ptr io_dig)
{
  // Add your implementation here
}

::Distrio::Error * Distrio_Manager_i::register_io_device (
  ::Distrio::Device_ptr io_dev)
{
  // Add your implementation here
}

::Distrio::Error * Distrio_Manager_i::unregister_io_digital (
  ::Distrio::Digital_ptr io_dig)
{
  // Add your implementation here
}

::Distrio::Error * Distrio_Manager_i::unregister_io_analog (
  ::Distrio::Analog_ptr io_ana)
{
  // Add your implementation here
}

::Distrio::Error * Distrio_Manager_i::unregister_io_device (
  ::Distrio::Device_ptr io_dev)
{
  // Add your implementation here
}

void Distrio_Manager_i::log_error (
  const ::Distrio::Error & error)
{
  // Add your implementation here
}

