#ifndef DISTIO_COMMON_IDL
#define DISTIO_COMMON_IDL

module Common {

	enum Error_code {
		SUCCESS,
		EINVAL,
		ENOTSUPPORTED
	};

	enum Error_level {
		DEBUG,
		INFO,
		WARNING,
		NORMAL,
		CRITICAL
	};

	struct Error_timestamp {
		longlong seconds;
		long nanoseconds;
	};

	struct Error {
		Error_code code;
		Error_level level;
		Error_timestamp time;
		long module_id;
		string description;
	};

};

#endif
