#ifndef DISTIO_CONTROLLER_IDL
#define DISTIO_CONTROLLER_IDL

#include "common.idl"
#include "io.idl"

module Controller {

	interface Manager {
		Common::Error digital (out IO::Digital_list io_list);
		Common::Error analog (out IO::Analog_list io_list);
		Common::Error device (out IO::Device_list dev_list);
		Common::Error register_io_digital (in IO::Analog io_ana);
		Common::Error register_io_analog (in IO::Digital io_dig);
		Common::Error register_io_device (in IO::Device io_dev);
		Common::Error unregister_io_digital (in IO::Digital io_dig);
		Common::Error unregister_io_analog (in IO::Analog io_ana);
		Common::Error unregister_io_device (in IO::Device io_dev);
		void log_error (in Common::Error error);
	};

};

#endif
